import Choose from "./choose";
import StyleYouChoose from "./YouChoose.module.scss";

export default function YouChoose() {
    return (
        <div className={StyleYouChoose.container}>
            <Choose />
            <div className={StyleYouChoose.box}>
                <div className={StyleYouChoose.box__ranking}>
                    <div className={StyleYouChoose.box__ranking__item}>
                        <div
                            className={
                                StyleYouChoose.box__ranking__item__poster_mini
                            }
                        >
                            IMG
                        </div>
                        <div
                            className={StyleYouChoose.box__ranking__item__title}
                        >
                            <h1
                                className={
                                    StyleYouChoose.box__ranking__item__title__h1
                                }
                            >
                                Title
                            </h1>
                        </div>
                        <div
                            className={StyleYouChoose.box__ranking__item__score}
                        >
                            SCORE
                        </div>
                    </div>
                    <div className={StyleYouChoose.box__ranking__item}>
                        <div
                            className={
                                StyleYouChoose.box__ranking__item__poster_mini
                            }
                        >
                            IMG
                        </div>
                        <div
                            className={StyleYouChoose.box__ranking__item__title}
                        >
                            <h1
                                className={
                                    StyleYouChoose.box__ranking__item__title__h1
                                }
                            >
                                Title
                            </h1>
                        </div>
                        <div
                            className={StyleYouChoose.box__ranking__item__score}
                        >
                            SCORE
                        </div>
                    </div>
                    <div className={StyleYouChoose.box__ranking__item}>
                        <div
                            className={
                                StyleYouChoose.box__ranking__item__poster_mini
                            }
                        >
                            IMG
                        </div>
                        <div
                            className={StyleYouChoose.box__ranking__item__title}
                        >
                            <h1
                                className={
                                    StyleYouChoose.box__ranking__item__title__h1
                                }
                            >
                                Title
                            </h1>
                        </div>
                        <div
                            className={StyleYouChoose.box__ranking__item__score}
                        >
                            SCORE
                        </div>
                    </div>
                    <div className={StyleYouChoose.box__ranking__item}>
                        <div
                            className={
                                StyleYouChoose.box__ranking__item__poster_mini
                            }
                        >
                            IMG
                        </div>
                        <div
                            className={StyleYouChoose.box__ranking__item__title}
                        >
                            <h1
                                className={
                                    StyleYouChoose.box__ranking__item__title__h1
                                }
                            >
                                Title
                            </h1>
                        </div>
                        <div
                            className={StyleYouChoose.box__ranking__item__score}
                        >
                            SCORE
                        </div>
                    </div>
                    <div className={StyleYouChoose.box__ranking__item}>
                        <div
                            className={
                                StyleYouChoose.box__ranking__item__poster_mini
                            }
                        >
                            IMG
                        </div>
                        <div
                            className={StyleYouChoose.box__ranking__item__title}
                        >
                            <h1
                                className={
                                    StyleYouChoose.box__ranking__item__title__h1
                                }
                            >
                                Title
                            </h1>
                        </div>
                        <div
                            className={StyleYouChoose.box__ranking__item__score}
                        >
                            SCORE
                        </div>
                    </div>
                    <div className={StyleYouChoose.box__ranking__item}>
                        <div
                            className={
                                StyleYouChoose.box__ranking__item__poster_mini
                            }
                        >
                            IMG
                        </div>
                        <div
                            className={StyleYouChoose.box__ranking__item__title}
                        >
                            <h1
                                className={
                                    StyleYouChoose.box__ranking__item__title__h1
                                }
                            >
                                Title
                            </h1>
                        </div>
                        <div
                            className={StyleYouChoose.box__ranking__item__score}
                        >
                            SCORE
                        </div>
                    </div>
                    <div className={StyleYouChoose.box__ranking__item}>
                        <div
                            className={
                                StyleYouChoose.box__ranking__item__poster_mini
                            }
                        >
                            IMG
                        </div>
                        <div
                            className={StyleYouChoose.box__ranking__item__title}
                        >
                            <h1
                                className={
                                    StyleYouChoose.box__ranking__item__title__h1
                                }
                            >
                                Title
                            </h1>
                        </div>
                        <div
                            className={StyleYouChoose.box__ranking__item__score}
                        >
                            SCORE
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
